nav/urls.py
from django.urls import path
from . import views

app_name = 'nav'

urlpatterns = [
    path('', views.index, name="index"),
]

todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns = [
    path('', views.index, name="index"),
    path('add_todo/', views.add_todo, name="add_todo"),
    path('delete_todo/<int:del_id>/', views.delete, name="delete"),
    path('update/<int:update_id>/', views.update, name="update"),
]

website_main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oldlogin/', include('login.urls')),
    path('accounts/', include('accounts.urls')),
    path('nav/', include('nav.urls')),
    path('', include('articles.urls')),
    path('todo/', include('todo.urls')),
]

todo/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import CASCADE


class TodoItem(models.Model):
    item = models.CharField(max_length=300)
    author = models.ForeignKey(User, default=None, on_delete=CASCADE)
    due = models.DateTimeField(null=True)
    created = models.DateTimeField()

todo/forms.py
from django import forms
from . import models


class CreateTodo(forms.ModelForm):
    class Meta:
        model = models.TodoItem
        fields = ['item', 'created', 'due']


class UpdateTodo(forms.ModelForm):
    class Meta:
        model = models.TodoItem
        fields = ['item', 'due']

todo/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from django.contrib.auth.decorators import login_required
from . import templates
from . import models
from .forms import CreateTodo, UpdateTodo

app_name = "todo"


@login_required(login_url="/accounts/login")
def test(request):
    return render(request, 'todo/all_todo.html')


@login_required(login_url="/accounts/login")
def index(request):
    items = models.TodoItem.objects.all().filter(author=request.user).order_by('created')
    return render(request, 'todo/all_todo.html', {'items': items})


@login_required(login_url="/accounts/login")
def add_todo(request):
    if request.method == "GET":
        form = CreateTodo()
    else:
        form = CreateTodo(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('todo:index')
    return render(request, 'todo/add_todo.html', {'form': form})


@login_required(login_url="/accounts/login")
def delete(request, del_id):
    obj = models.TodoItem.objects.get(id=del_id)
    obj.delete()
    return redirect('todo:index')


@login_required(login_url="/accounts/login")
def update(request, update_id):
    if request.method == "GET":
        obj = get_object_or_404(models.TodoItem, id=update_id)
        form = UpdateTodo(initial={'item': obj.item, 'created':obj.created, 'due':obj.due})
    else:
        obj = get_object_or_404(models.TodoItem, id=update_id)
        form = UpdateTodo(request.POST, instance=obj)
        if form.is_valid():
            form.save()
            return redirect('todo:index')
    return render(request, 'todo/update_todo.html', {'form': form, 'obj': obj})

todo/templates/todo/add_todo.html
{% extends 'articles/base.html' %}

{% block content %}
    <form method="post" action="{% url 'todo:add_todo' %}">
    {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="create">
    </form>
{% endblock content %}

todo/templates/todo/all_todo.html
{% extends 'articles/base.html' %}

{% block content %}
    <form action="{% url 'todo:add_todo' %}" method="get">
        <input type="submit" value="New">
    </form>

    <table style="width: 100%; border: 2px solid black">
        <tr style="border: 2px solid black">
            <th>Todo Item</th>
            <th>Date Due</th>
            <th>Date Created</th>
            <th>Actions</th>
        </tr>

    {% for object in items %}
        <tr style="border: 2px solid black">
            <td>{{ object.item }}</td>
            <td>{{ object.due }}</td>
            <td>{{ object.created }}</td>
            <td>
                <form action="{% url 'todo:delete' object.id %}" method="post" style="margin: auto">
                    {% csrf_token %}
                    <input type="submit" value="Completed" style="background: green; color: white">
                </form>
                <form action="{% url 'todo:update' object.id %}" method="get" style="margin: auto">
                    <input type="submit" value="Update" style="background: #ff9933">
                </form>
            </td>
        </tr>
    {% endfor %}
    </table>
{% endblock content %}

todo/templates/todo/update_todo.html
{% extends 'articles/base.html' %}
{% block content %}
    <form method="post" action="{% url 'todo:update' obj.id %}">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="update">
    </form>
{% endblock content %}