accounts/urls.py
from django.conf.urls import url
from . import views

app_name = 'accounts'

urlpatterns = [
    url(r'^signup/$', views.signup_view, name="signup"),
    url(r'^login/$', views.login_view, name="login"),
    url(r'^logout/$', views.logout_view, name="logout"),
]

articles/urls.py
from django.conf.urls import url
from . import views
from django.urls import path

app_name = 'articles'

urlpatterns = [
    path('', views.home, name="home"),
    path('add_article/', views.add_article, name="add_article"),
    path('article_page/<int:article_id>/', views.article_page, name="details"),
    path('update_article/<int:article_id>/', views.update_article, name="update"),
    path('delete_article/<int:article_id>/', views.delete_article, name="delete")
]

nav/urls.py
from django.urls import path
from . import views

app_name = 'nav'

urlpatterns = [
    path('', views.index, name="index"),
]

todo/urls.py
from django.urls import path
from . import views

app_name = "todo"
urlpatterns = [
    path('', views.index, name="index"),
    path('add_todo/', views.add_todo, name="add_todo"),
    path('delete_todo/<int:del_id>/', views.delete, name="delete"),
    path('update/<int:update_id>/', views.update, name="update"),
]

website_main/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('oldlogin/', include('login.urls')),
    path('accounts/', include('accounts.urls')),
    path('nav/', include('nav.urls')),
    path('', include('articles.urls')),
    path('todo/', include('todo.urls')),
]

articles/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models import CASCADE


class Article(models.Model):
    title = models.CharField(max_length=200)
    date = models.DateTimeField()
    body = models.TextField()
    author = models.ForeignKey(User, default=None, on_delete=CASCADE)

    def __str__(self):
        return self.title

    def snippet(self):
        return self.body[:100] + "..."

articles/forms.py
from django import forms
from . import models


class CreateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'date', 'body']


class UpdateArticle(forms.ModelForm):
    class Meta:
        model = models.Article
        fields = ['title', 'date', 'body']

articles/views.py
from django.shortcuts import render, redirect, get_object_or_404
from . import forms
from . import models
from django.contrib.auth.decorators import login_required


@login_required(login_url="/accounts/login")
def home(request):
    articles = models.Article.objects.all().filter(author=request.user).order_by('date')
    return render(request, 'articles/index.html', {'articles': articles})


@login_required(login_url="/accounts/login")
def add_article(request):
    if request.method == "GET":
        form = forms.CreateArticle()
    else:
        form = forms.CreateArticle(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            instance.author = request.user
            instance.save()
            return redirect('articles:home')
    return render(request, 'articles/add_article.html', {'form': form})


@login_required(login_url="/accounts/login")
def article_page(request, article_id):
    try:
        article = models.Article.objects.get(id=article_id)
    except models.Article.DoesNotExist:
        return redirect('articles:home')
    return render(request, 'articles/article_detail.html', {'article': article})


@login_required(login_url="/accounts/login")
def update_article(request, article_id):
    if request.method == "GET":
        article = get_object_or_404(models.Article, id=article_id)
        form = forms.UpdateArticle(initial={'title': article.title, 'date': article.date, 'body': article.body})
    else:
        article = get_object_or_404(models.Article, id=article_id)
        form = forms.UpdateArticle(request.POST, instance=article)
        if form.is_valid():
            form.save()
        return redirect('articles:home')
    return render(request, 'articles/update.html', {'form': form, 'article': article})


@login_required(login_url="/accounts/login")
def delete_article(request, article_id):
    article = get_object_or_404(models.Article, id=article_id)
    article.delete()
    return redirect('articles:home')

articles/templates/articles/add_article.html
{% extends "articles/base.html" %}

{% block content %}
    <form name="add_article" method="post" action="{% url 'articles:add_article' %}">
        {% csrf_token %}
        <table>
            {{ form.as_table }}
        </table>
        <input type="submit" value="create new article">
    </form>
{% endblock content %}

articles/templates/articles/article_detail.html
{% extends 'articles/base.html' %}

{% block content %}
<h1>{{ article.title }}</h1>

    <p>{{ article.date }}</p>
    <p>{{ article.body }}</p>
    <div class="dropdown-divider"></div>
    <form method="get" action="{% url 'articles:update' article.id %}">
        <input type="submit" value="update">
    </form>
    <form method="get" action="{% url 'articles:delete' article.id %}">
        <input style="background: red" type="submit" value="delete">
    </form>
{% endblock content %}

articles/templates/articles/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>

  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
  <meta name="description" content="">
  <meta name="author" content="">

  <title>Aryaman</title>

  <!-- Bootstrap core CSS -->
  <link href="{% static 'vendor/bootstrap/css/bootstrap.min.css' %}" rel="stylesheet">

  <!-- Custom styles for this template -->
  <link href="{% static 'css/simple-sidebar.css' %}" rel="stylesheet">

</head>

<body>

  <div class="d-flex" id="wrapper">

    <!-- Sidebar -->
    <div class="bg-light border-right" id="sidebar-wrapper">
      <div class="sidebar-heading">Aryaman </div>
      <div class="list-group list-group-flush">
        <a href="{% url 'articles:home' %}" class="list-group-item list-group-item-action bg-light">Articles</a>
        <a href="{% url 'todo:index' %}" class="list-group-item list-group-item-action bg-light">Todo List</a>
          <form method="post" action="{% url 'accounts:logout' %}">
            {% csrf_token %}
              <input type="submit" class="list-group-item list-group-item-action bg-danger" style="color: white" value="logout">
          </form>
              <!--
        <a href="#" class="list-group-item list-group-item-action bg-light">Overview</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">Events</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">Profile</a>
        <a href="#" class="list-group-item list-group-item-action bg-light">Status</a>
        -->
      </div>
    </div>
    <!-- /#sidebar-wrapper -->

    <!-- Page Content -->
    <div id="page-content-wrapper">

      <nav class="navbar navbar-expand-lg navbar-light bg-dark border-bottom">
        <button class="btn btn-primary" id="menu-toggle">Nav</button>

        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>


        <div class="collapse navbar-collapse" id="navbarSupportedContent">

            <ul class="navbar-nav ml-auto mt-2 mt-lg-0">
                <!--
            <li class="nav-item active">
              <a class="nav-link" href="#">Home <span class="sr-only">(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="#">Link</a>
            </li>
            -->
            <li class="nav-item dropdown">
                <!--
              <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" style="color: #ff9933">
                Article Options
              </a>-->
              <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
                <!--
                  <a class="dropdown-item" href="{% url 'articles:add_article' %}">Create new article</a>
                -->
                <!--
                <div class="dropdown-divider"></div>

                <a class="dropdown-item" href="{% url 'accounts:logout' %}">Logout</a>
                -->
              </div>
            </li>
          </ul>
        </div>
      </nav>

      <div class="container-fluid">
        {% block content %}
          {% endblock content %}
          <!--
          <h1 class="mt-4">Simple Sidebar</h1>
        <p>The starting state of the menu will appear collapsed on smaller screens, and will appear non-collapsed on larger screens. When toggled using the button below, the menu will change.</p>
        <p>Make sure to keep all page content within the <code>#page-content-wrapper</code>. The top navbar is optional, and just for demonstration. Just create an element with the <code>#menu-toggle</code> ID which will toggle the menu when clicked.</p>
      -->
      </div>
    </div>
    <!-- /#page-content-wrapper -->

  </div>
  <!-- /#wrapper -->

  <!-- Bootstrap core JavaScript -->
  <script src="{% static 'vendor/jquery/jquery.min.js' %}"></script>
  <script src="{% static 'vendor/bootstrap/js/bootstrap.bundle.min.js' %}"></script>

  <!-- Menu Toggle Script -->
  <script>
    $("#menu-toggle").click(function(e) {
      e.preventDefault();
      $("#wrapper").toggleClass("toggled");
    });
  </script>

</body>

</html>

articles/templates/articles/index.html
{% extends "articles/base.html" %}

{% block content %}
    <h2>All articles</h2>
    <form action="{% url 'articles:add_article' %}" method="get">
        <input type="submit" value="New">
    </form>
    <ul>
    {% for Article in articles %}
        <li>
            <h4>{{ Article.title }}<h4>

        </li>
        {{ Article.snippet }}
        <form method="get" action="{% url 'articles:details' Article.id %}">
                <input  type="submit" value="detail">
            </form>
     <div class="dropdown-divider"></div>
    {% endfor %}
    <ul>
{% endblock content %}

articles/templates/articles/update.html
{% extends 'articles/base.html' %}

{% block content %}
    <h4>Update</h4>
    <form action="{% url 'articles:update' article.id %}" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="make changes">
    </form>
{% endblock content %}